# Generated by Django 5.0.14 on 2026-09-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="can_change_password",
            field=models.BooleanField(
                default=False,
                help_text="Students only: enables the self-service password-change flow for this account.",
            ),
        ),
    ]
