# Generated by Django 5.0.14 on 2026-09-19 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
        ("core", "0002_classsubjectteacher"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubjectAttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("confirmed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "confirmed_via",
                    models.CharField(
                        choices=[("telegram", "Telegram button"), ("web", "Platform")],
                        default="telegram",
                        max_length=20,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_attendance_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="core.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-confirmed_at"],
            },
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="related_subject_attendance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="attendance.subjectattendancerecord",
            ),
        ),
        migrations.AddConstraint(
            model_name="subjectattendancerecord",
            constraint=models.UniqueConstraint(
                fields=("student", "subject", "date"),
                name="one_subject_confirmation_per_day",
            ),
        ),
    ]
